services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PATH: ${MONGO_PATH}
      MONGO_USER: ${MONGO_USER}
      NODE_ENV: ${NODE_ENV}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PORT: ${PORT}
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5000:5000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mongo-data: